parameter_clean_functions_map <- tibble::enframe(
  c(
    settlement_date = "format_date",
    period = "check_period",
    year = NA_character_,
    month = "format_month",
    week = NA_character_,
    start_date = "format_date",
    end_date = "format_date",
    start_time = "format_time",
    end_time = "format_time",
    service_type = NA_character_,
    event_start = "format_date",
    event_end = "format_date",
    publication_from = "format_date",
    publication_to = "format_date",
    participant_id = NA_character_,
    asset_id =NA_character_,
    event_type =NA_character_,
    fuel_type = NA_character_,
    message_type = NA_character_,
    message_id = NA_character_,
    unavailability_type = NA_character_,
    active_flag = NA_character_,
    sequence_id = NA_character_,
    from_date = "format_date",
    to_date = "format_date",
    settlement_period = "check_period",
    bm_unit_id = NA_character_,
    lead_party_name = NA_character_,
    ngc_bm_unit_name = NA_character_,
    from_cleared_date = "format_date",
    to_cleared_date = "format_date",
    is_two_day_window = NA_character_,
    from_datetime = "format_datetime",
    to_datetime = "format_datetime",
    from_settlement_date = "format_date",
    to_settlement_date = "format_date",
    fuel_type = NA_character_,
    balancing_service_volume = NA_character_,
    zone_identifier = NA_character_,
    trade_name = NA_character_,
    trade_type = NA_character_
  ), name = "name", value = "fn"
)
